"""=create progeny table

Revision ID: 96771670b47d
Revises: b6212799ab60
Create Date: 2019-02-16 12:04:35.163984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96771670b47d'
down_revision = 'b6212799ab60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progeny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progeny')
    # ### end Alembic commands ###
